name: 'Magento 2 integration tests'
author: 'ExtDN'
description: 'runs integration tests for given Magento 2 open source version'
services:
  mysql:
    image: mysql:5.7
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SQL_TO_RUN: 'GRANT ALL ON *.* TO "root"@"%";'
    ports:
      - 3306:3306
    options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
inputs:
  extension_vendor:
    description: 'Your extension vendor name'
    required: true
  extension_module:
    description: 'Your extension module name'
    required: true
  extension_source:
    description: 'Relative path to your extension source within your repository'
  ce_version:
    description: 'Magento 2 Open Source version number'
    required: true
    default: '2.3.5'
  php:
    description: 'version of php to use: 7.2 or 7.3 or 7.4'
    default: '7.3'
runs:
  using: 'docker'
  image: 'docker://yireo/github-actions-magento-integration-tests:latest'
branding:
  icon: 'code'  
  color: 'green'

